name: 'WordPress Props'
description: 'Leaves a list of all contributors associated with a pull request and linked issues in a comment for use within merge commits messages.'
inputs:
  token:
    description: 'GitHub secret token.'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
